### ISSUE TITLE
Report allocation

### ISSUE THREAD

**Issue by weipeng404** [ruoqizzz/Scale-invariant-CNNs#8]
- Abstract: Ruoqi

Introduction
- Convolutional Neural Networks & Equivariance and Invariance: Wei
- Locally Scale-Invariant Convolutional Neural Networks: Wei
- Scale Steerable Filters for Locally Scale-Invariant Convolutional Neural Networks: Wei
- Antialised CNN: Ruoqi

Dataset
- MNIST & MNIST-Scale: Wei
- FMNIST & FMNIST-Scale: Wei
- OralCancer & OralCancer-Scale: Wei

Experiment
- Experiment Environment: Wei
- Experiment Design: Wei
- Result: Ruoqi

Discussion & Future Work: Ruoqi

Conclusion: Ruoqi

**Complete own part before the end of Feb 01**

**Comment by wsgdrfz** [comment]
I just found you assign this to me. 
Thanks for the information and reminder!
🤬🤬
